apiVersion: v1
kind: Service
metadata:
  name: serverjs-service
spec:
  type: NodePort
  selector:
    app: serverjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080